title = "Two Swords"
repo_url = "https://github.com/sean-clayton/two-swords"
repo_cc_license_url = "https://github.com/sean-clayton/two-swords/blob/main/COPYING-CC-BY-SA"
repo_license_url = "https://github.com/sean-clayton/two-swords/blob/main/COPYING-AGPL"
itch_url = "https://seanclayton.itch.io/two-swords"
author = "Sean-Patrick Ortencio Clayton"

[config]
theme = "#{THEME}#" # This is modified by CI/CD
media = "#{MEDIA}#" # This is modified by CI/CD
git_sha = "#{GITHUB_SHA}" # This is modified by CI/CD
version = "NIGHTLY" # This is modified by CI/CD
version_url = "#{VERSION_URL}#" # This is modified by CI/CD
wip = true
