title = "Two Swords"
repo_url = "https://github.com/sean-clayton/two-swords"
repo_cc_license_url = "https://github.com/sean-clayton/two-swords/blob/main/COPYING-CC-BY-SA"
repo_license_url = "https://github.com/sean-clayton/two-swords/blob/main/COPYING-AGPL"
itch_url = "https://seanclayton.itch.io/two-swords"
author = "Sean-Patrick Ortencio Clayton"
