name: Build PDF

on:
  workflow_call:

jobs:
  create-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: yusancky/setup-typst@v2
        with:
          version: latest

      - run: mkdir dist

      - name: Build PDF
        run: typst compile --font-path fonts two-swords.typ dist/TwoSwords-${{ github.ref_name#v }}.pdf

      - uses: actions/upload-artifact@v3
        with:
          name: pdf-artifact
          path: dist
