name: Deploy to Itch
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yusancky/setup-typst@v2
        with:
          version: latest
      - run: |
          mkdir dist
          typst compile --font-path fonts white-wolf.typ dist/White\ Wolf.pdf
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Butler Push
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_CREDENTIALS }}
          gameData: dist
          itchUsername: seanclayton
          itchGameId: white-wolf
          buildChannel: book
