name: Deploy to Itch

on:
  release:
    types: [released]

jobs:
  release-to-itch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ${{ github.repository }}/.github/workflows/build-pdf.yml@main

      - name: Extract Version From Tag
        id: get_version
        uses: battila7/get-version-action@v2

      - uses: actions/download-artifact@v3
        with:
          name: pdf-artifact

      - name: Butler Push
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_CREDENTIALS }}
          gameData: dist
          itchUsername: seanclayton
          itchGameId: two-swords
          buildChannel: book
          buildNumber: ${{ steps.get_version.outputs.version-without-v }}
