name: Deploy to Itch

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract Version From Tag
        id: get_version
        uses: battila7/get-version-action@v2

      - uses: yusancky/setup-typst@v2
        with:
          version: latest

      - run: mkdir dist

      - name: Build PDF
        run: typst compile --font-path fonts white-wolf.typ dist/WhiteWolf-${{ steps.get_version.outputs.version-without-v }}.pdf

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Extract Version From Tag
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Butler Push
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_CREDENTIALS }}
          gameData: dist
          itchUsername: seanclayton
          itchGameId: white-wolf
          buildChannel: book
          buildNumber: ${{ steps.get_version.outputs.version-without-v }}
