name: Deploy to Itch

on:
  release:
    types: [released]

jobs:
  get-pdf-artifacts:
    uses: sean-clayton/two-swords/.github/workflows/build-pdf.yml@main

  itch-deploy:
    runs-on: ubuntu-latest
    needs: get-pdf-artifacts
    steps:
      - uses: actions/checkout@v3

      - name: Get Version
        uses: maltoze/get-version-action@v1
        id: get_version

      - uses: actions/download-artifact@v3
        with:
          name: pdf-artifact
          path: dist

      - run: mkdir COPYING
      - run: cp COPYING-CC-BY-SA COPYING
      - run: cp COPYING-AGPL COPYING

      - run: wget https://github.com/${{ github.repository }}/archive/${{ github.ref }}.zip -O source.zip

      - name: Butler Push PDF
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_CREDENTIALS }}
          gameData: dist
          itchUsername: seanclayton
          itchGameId: two-swords
          buildChannel: book
          buildNumber: ${{ steps.get_version.outputs.version-without-v }}

      - name: Butler Push COPYING
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_CREDENTIALS }}
          gameData: COPYING
          itchUsername: seanclayton
          itchGameId: two-swords
          buildChannel: copying
          buildNumber: ${{ steps.get_version.outputs.version-without-v }}

      - name: Butler Push Source ZIP
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_CREDENTIALS }}
          gameData: source.zip
          itchUsername: seanclayton
          itchGameId: two-swords
          buildChannel: source-code
          buildNumber: ${{ steps.get_version.outputs.version-without-v }}
