name: Deploy to Itch

on:
  release:
    types: [released]

jobs:
  get-pdf-artifacts:
    uses: sean-clayton/two-swords/.github/workflows/build-pdf.yml@main

  itch-deploy:
    runs-on: ubuntu-latest
    needs: get-pdf-artifacts
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: pdf-artifact
          path: dist

      - name: Butler Push
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_CREDENTIALS }}
          gameData: dist
          itchUsername: seanclayton
          itchGameId: two-swords
          buildChannel: book
          buildNumber: ${{ github.ref_name#v }}
