name: Nightly Build

on:
  workflow_dispatch:
  schedule:
    # Daily cron job (at 00:00)
    - cron: "0 0 * * *"

jobs:
  get-pdf-artifacts:
    uses: sean-clayton/two-swords/.github/workflows/build-pdf.yml@main

  nightly-build:
    runs-on: ubuntu-latest
    needs: get-pdf-artifacts
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: pdf-artifact
          path: dist

      - uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            dist/*.pdf
          tag: nightly
          rm: true
