name: Add Artifacts to Release

on:
  release:
    types: [published]

jobs:
  get-pdf-artifacts:
    uses: sean-clayton/two-swords/.github/workflows/build-pdf.yml@main

  add-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract Version From Tag
        id: get_version
        uses: battila7/get-version-action@v2

      - uses: actions/download-artifact@v3
        with:
          name: pdf-artifact

      # Create a release for this specific version
      - name: Update Release with Files
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # Set this to false if you want to prevent updating existing releases
          name: ${{ github.event.release.name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: dist/*.pdf
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
